### PR TITLE
from krigar1184:works_pagination

### PR DESCRIPTION
**Pull request by eshellman**

### CODE REVIEW

**Comment by v-kolesnikov** [comment]
Thanks a lot @krigar1184 and @eshellman ! 🎉 
Looking forward these changes! 😍

**Comment by eshellman** [comment]
- I had misdocumented the api addition.
- must always sanitize incoming data
- and catch the errors you expect
@krigar1184 let me know if this looks good.

**Comment by krigar1184** [comment]
@eshellman thanks, looks perfect!

**Comment by eshellman** [comment]
Running on production! Thank you for contributing to unglue.it.

**Pull request merged**
